/*
 * $Id $
 *
 * Copyright 2005 Sun Microsystems
 *
 * Initially developed by Antonio Vieiro (vieiro@dev.java.net).
 *
 * This software is released under the Common Development and Distribution
 *  License, version 1.0. See http://www.opensource.org/licenses/cddl1.php
 *  for details.
 *
 * This software is distributed on an "AS IS" basis, without warranty of any
 *  kind, either express or implied.
 *
 * All this stuff basically means that you can use this source code in your
 *  software, either proprietary or not. See 
 *  http://www.opensolaris.org/os/about/faq/licensing_faq/ for interesting
 *  information about the CDDL license.
 *
 */
package org.jdesktop.swingworker.demos.mandelbrot.view.canvas;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import org.jdesktop.swingworker.demos.mandelbrot.model.MandelbrotModel;

/**
 * BufferedImagePane is a JPanel that paints an image.
 * @author Antonio Vieiro (vieiro@dev.java.net)  $Author$
 */
public class BufferedImagePane extends javax.swing.JPanel
{
  private BufferedImage image;
  private Dimension imageSize;
  
  /**
   * Creates new form BufferedImagePane 
   */
  public BufferedImagePane()
  {
    initComponents();
    image = null;
    imageSize = new Dimension(640,480);
  }
  
  public Dimension getPreferredSize()
  {
    return imageSize;
  }
  
  public Dimension getMinimumSize()
  {
    return new Dimension(200,100);
  }
  
  public void setImage( BufferedImage anImage )
  {
    imageSize = new Dimension( anImage.getWidth(), anImage.getHeight() );
    image = anImage;
    repaint();
  }
  
  public void paintComponent( Graphics g )
  {
    if ( image != null )
    {
      boolean available = g.drawImage(image,0,0,null);
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    setLayout(new java.awt.BorderLayout());

    setBackground(new java.awt.Color(255, 255, 255));
    setOpaque(false);
  }
  // </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  
}
